### ISSUE TITLE
CSP violations

### ISSUE THREAD

**Issue by amasad** [6to5/acorn-6to5#13]
Some JS environments (my use case is github atom) enforces CSP which means eval, and the likes (`new Function` etc) are not allowed. It seems like this library does a lot of code generation at runtime. I was able to hack around it so it's not a blocking issue, but it'd be great to get rid of those if they're not essential to perf.

**Comment by amasad** [comment]
https://github.com/RReverser/acorn-csp Seems to solve the problem. Is it possible to run this through it in a prepublish step?
cc @RReverser

**Comment by RReverser** [comment]
@amasad It's already integrated in upstream Acorn and merged here. Check this section from upstream docs: [Using Acorn in an environment with a Content Security Policy](https://github.com/marijnh/acorn#using-acorn-in-an-environment-with-a-content-security-policy) (it should work for `acorn-6to5` as well).

However I don't see why would you want to use `acorn-6to5` outside 6to5 as [it's README](https://github.com/6to5/acorn-6to5) clearly states that

> acorn-6to5 is not supported outside of 6to5 usage

**Comment by amasad** [comment]
Oh I want to use 6to5, Im just saying if this can be published to npm after
the code is generated then 6to5 can consume this package with no eval

**Comment by sebmck** [comment]
@amasad Is the performance penalty worth it just for browsers? I guess I could add a build step and add `acorn_csp.js` to `browser` in `package.json`.

**Comment by RReverser** [comment]
@sebmck Note that in most cases it can be easily disabled right in browser, especially since 6to5 is used on developer's machine in developer's browser and not distributed to various end users from some public server.

**Comment by amasad** [comment]
@sebmck I haven't done any benchmarking but I'm personally fine with the perf hit for the CSP version. Most of the work we'll do in node anyway. I don't know if Atom respects the browser field package.json, but I have strong feeling it doesn't. Maybe we can have a `csp: true` in 6to5 that makes it csp safe.

@RReverser how do you disable it? we'd have to do it programmatically I don't want the devs on the project to have to do any work to start writing code.

To clarify our use case is that we're building atom packages written in ES6/7, React, and Flow and in addition to compiling the packages ahead of time with 6to5 in node (which works fine) we have a watcher that runs inside atom that we want to use 6to5 with to recompile packages on the fly as they're being saved.

**Comment by sebmck** [comment]
@RReverser What kind of performance penalty would there be by using the CSP version? I'm open to making it the default if the implications are minimal.

**Comment by sebmck** [comment]
Actually, I see that `bin/without_eval` just inlines the compiled function so the performance will be the same?

**Comment by RReverser** [comment]
@sebmck Theoretically it should be, except that the size of library will be bigger. But better to check.

**Comment by amasad** [comment]
ah, ok, I thought it created functions while doing the work, if this is done at initialization then I don't see how this would be a perf benefit

**Comment by sebmck** [comment]
Future releases of 6to5 will include the CSP version of acorn-6to5.

**Comment by amasad** [comment]
awesome, thanks!

**Comment by sebmck** [comment]
Available as of 6to5 2.12.0

**Comment by amasad** [comment]
thanks @sebmck!
