### ISSUE TITLE
Flow types on default parameters 

### ISSUE THREAD

**Issue by sebmck** [6to5/acorn-6to5#24]
Currently has to be:

```javascript
function foo(bar = "foobar": String) {

}
```

Should be

```javascript
function foo(bar: String = "foobar") {

}
```

**Comment by sebmck** [comment]
Looks like `acorn-6to5` supports type annotations inside of destructuring definitions. `esprima-fb` and `flow` don't support this. It probably should since it seems pretty logical.

**Comment by RReverser** [comment]
Probably worth raising an issue in https://github.com/facebook/esprima

**Comment by sebmck** [comment]
@RReverser I asked in the #flowtype IRC and got no response. I also check the actual flow parser and it doesn't support it. There'll have to be a case added to make it illegal inside destructuring. `parseAssignableList` is only called on function params and arrays right? Should be able to just add a `noTypes` param or something.

**Comment by RReverser** [comment]
@sebmck In fact, I'd rather agree that destructured variable declarations / function params should support type annotations as well, it's pretty logical. That's why I propose raising an issue in either esprima-fb or [flow](https://github.com/facebook/flow) for proper discussion.

**Comment by sebmck** [comment]
@RReverser Yeah I know, I'm just not comfortable with allowing illegal syntax, even temporarily. I've opened an issue at facebook/flow#235

**Comment by RReverser** [comment]
@sebmck This might be considered part of playground features then :P But I do understand your concerns.

**Comment by gabelevi** [comment]
> I asked in the #flowtype IRC and got no response

Sorry! I had just gone to sleep when you asked :P

**Comment by sebmck** [comment]
@gabelevi It's all good! Sorry to be a bother.
